### ISSUE TITLE
关于许可证

### ISSUE THREAD

**Issue by chuangzhu** [Sucareto/Android_HID_Keyboard#1]
谢谢你做的这个超棒的工具！请问你打算开源这个项目（不仅仅是开放源代码），也就是选择一个开源许可证吗？关于如何选择开源许可证可以参考这个页面：

https://choosealicense.rustwiki.org/

**Comment by Sucareto** [comment]
谢谢，该项目还没完成，暂时没有选择开源许可证的想法。
