### ISSUE TITLE
软件最低要求Android版本是多少？Android8.0.0不能用

### ISSUE THREAD

**Issue by iiowoii3389** [Sucareto/Android_HID_Keyboard#3]
![Screenshot_2023-12-24-18-26-17-950_com miui packageinstaller](https://github.com/Sucareto/Android_HID_Keyboard/assets/60783918/52c3deb0-87b1-4d13-ba5c-d5e350d43707)

**Comment by iiowoii3389** [comment]
USB Gadget Tool好像也没有正常工作😂
![Screenshot_2023-12-24-19-27-23-999_com android settings](https://github.com/Sucareto/Android_HID_Keyboard/assets/60783918/61ea7376-a01d-4fea-876d-5e9d30563753)
![Screenshot_2023-12-24-19-27-54-758_net tjado usbgadget](https://github.com/Sucareto/Android_HID_Keyboard/assets/60783918/4cb3094f-02a6-408b-bd86-ea93fdbe5448)
😭这个/config/usb_gadget/xxxx文件夹好像只有4.x内核和Android10以上会有？

**Comment by Sucareto** [comment]
本程序目前设定支持的最低版本是 [Android 10 (API level 29)](https://github.com/Sucareto/Android_HID_Keyboard/blob/v1.5.1/app/build.gradle#L10)，除此之外 [USB Gadget Tool](https://github.com/tejado/android-usb-gadget) 还要求内核支持 ConfigFS 才能用。
从截图来看，应该是内核不支持 ConfigFS 了。

**Comment by iiowoii3389** [comment]
![Screenshot_20231226-000647_USB Gadget Tool](https://github.com/Sucareto/Android_HID_Keyboard/assets/60783918/607c3feb-dcae-42d3-be75-525cc15b097b)
![Screenshot_20231226-001345_设置](https://github.com/Sucareto/Android_HID_Keyboard/assets/60783918/aa0ccc4e-9f5d-4dce-9239-4490f8930acc)
换了个设备，刷了其他的系统能用了!!!不过为啥鼠标在bios里移动会漂移()系统里不会

**Comment by iiowoii3389** [comment]
Redmi 5s Plus
Android12
Linux4.9
![IMG_20231226_001222](https://github.com/Sucareto/Android_HID_Keyboard/assets/60783918/93a1fc07-43b7-42f0-984c-c6a0955c8285)

**Comment by Sucareto** [comment]
> 换了个设备，刷了其他的系统能用了!!!不过为啥鼠标在bios里移动会漂移()系统里不会

用正常的鼠标设备试下看看是不是 BIOS 的问题？
鼠标的实现很随意，还没有认真检查过...我也试一下看看好了。

**Comment by Sucareto** [comment]
试试这个[v1.5.2](https://github.com/Sucareto/Android_HID_Keyboard/releases/tag/v1.5.2)，问题应该修复了。
