### ISSUE TITLE
电涌问题

### ISSUE THREAD

**Issue by Rsrxdalxh** [Sucareto/Android_HID_Keyboard#4]
我在我的小米平板4上使用时，电脑会提示“USB 端口上的电涌” ，这个日志是我在USB Gadget Tool里复制粘贴下来的，不知道有没有用处
我用的是第三方安卓类原生系统

![Screenshot_20240303-111910_](https://github.com/Sucareto/Android_HID_Keyboard/assets/109501145/5ef505e2-abbc-4535-a44a-558963f90be1)

(![KQD8LZD9_BKJ7R6R~{0LB@7](https://github.com/Sucareto/Android_HID_Keyboard/assets/109501145/427a4177-f11f-46fd-a118-2132b2b867d0))

[log.txt](https://github.com/Sucareto/Android_HID_Keyboard/files/14472650/log.txt)

**Comment by Sucareto** [comment]
在未使用 USB Gadget Tool 启用键盘功能时，会提示这个吗？
在使用 USB Gadget Tool 启用键盘功能后，未启用本软件进行键盘鼠标操作时，会提示这个吗？
更换到其他 USB 接口，是否有变化呢？

**Comment by Rsrxdalxh** [comment]
未使用 USB Gadget Tool 启用键盘功能时，没有这个提示，启用键盘鼠标功能后也没有，是在打开“HID键盘”后才有这个提示，更换其他USB口也不行，我第一次是插在我的usb hub上的，然后我又直接插到主板的USB接口上，还是会有电涌提示。
还有一点就是，打开“HID键盘”后，充电速度明显提升，在锁屏界面显示的电流在0.6mA左右，有充电器一半速度，当平板电量到达90%以上时，就会有这个提示，我使用软件Scene限制充电电流，似乎并不起作用。

**Comment by Sucareto** [comment]
这个情况有点奇怪，我也找个手机试试看。
本软件未对系统文件进行修改，只是向 `/dev/hidg0` 和 `/dev/hidg1` 分别发送了键码数据。

请帮忙测试以下操作：
1. 重启手机
2. 打开 USB Gadget Tool，启用 USB Gadget Tool 功能
3. 接上数据线，连接到 USB 口
4. 观察是否有电涌提示
5. 打开任意终端软件，如 [Terminal](https://play.google.com/store/apps/details?id=com.qamar.terminal) 或 [Termux](https://github.com/termux/termux-app/releases)，如果不想在手机操作命令行，使用`网络 ADB 调试`连接也可以
6. 在终端内运行命令 `su` 获取 root 身份
7. 输入以下两个命令测试效果，这两个命令用于发送键码实现操作：
`echo -ne "\\x08\\x00\\x00\\x00\\x00\\x00\\x00\\x00" > /dev/hidg0`
命令效果：左侧 Win 键被按住
`echo -ne "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00" > /dev/hidg0`
命令效果：所有按键被松开
8. 观察按键操作是否生效，同时注意电涌提示是否还会出现
9. 如果电涌提示未出现，打开本软件，但不执行任何按键操作，再次观察电涌提示是否会出现

**Comment by Rsrxdalxh** [comment]
我进行了上面的操作，第一次连接电脑打开USB Gadget Tool时就弹出了电涌提示，我又断开数据线等待了几分钟，再次连接电脑，打开USB Gadget Tool，这时候又没有电涌提示，我通过adb执行了那两行命令，电脑有反应，并且没有电涌提示，又执行了一次，也没有。
然后我打开HID键盘，不执行按键操作时没有电涌提示，但是持续连接了有半小时后，我尝试使用平板码字，又出现了问题，按下按键的反馈不流畅，并且不到一分钟就弹出了电涌提示。
不过在此之前，就是第一次弹出电涌提示后，我等待电涌提示消失后，尝试再次将数据线连接电脑时，我还没有插进平板的UBS-C口，仅仅是碰到了外壳（中框应该是金属），电脑也弹出了电涌提示，我不确定是误判还是我的数据线，或者我的平板的问题。

**Comment by Sucareto** [comment]
会不会是线或平板的问题呢？
我使用我的 OnePlus 7 Pro 在剩余电量 40% 和 90% 时进行多次测试，分别使用了原装 A to C 线（支持 Warp 闪充）和 C to C 线（支持 PD 快充），接入电脑的 2.0 和 3.0 A 口，10G 和 20G 的 C 口，都未出现电涌提示，使用充电电流检测软件，最高充电电流未超过 350mA。

然后，在 USB Gadget Tool 创建的配置文件里，发现了最大电流的配置信息，不知道修改这个配置文件是否有效果。
检查当前配置定义的最大电流值：
`cat /config/usb_gadget/keyboard/configs/c.1/MaxPower`
可以看到返回的数值是 `120`，单位是 mA。
在任意 Linux 系统可以通过 `lsusb -V` 检查到这个数值，观察到我在用的键盘返回的数值是 100mA，或许可以根据你的设备来进行修改？
修改为 100mA：
`echo 100 > /config/usb_gadget/keyboard/configs/c.1/MaxPower`
修改命令可以多次重复执行以测试不同的数值。
如果更换线材没有效果的话，可以尝试这个方法，但**未确定是否有其他影响**。。
这个配置文件是在开机后第一次打开 USB Gadget Tool 时创建的，重启并不会保留，如果遇到问题可以重启恢复。

**Comment by Rsrxdalxh** [comment]
可能是我的线问题，刚刚我的电脑只连接了鼠标和键盘，还有一根魅蓝的快充线（我一直使用这根线来连接平板），这根线没有连接任何设备，刚刚可能就是碰到它了，我的电脑又出现了电涌提示。现在我换了一根c to c的线，现在这段字就是用平板码的，已经没有电涌提示了，麻烦你了，弄了这么久原来是我的线的问题，谢谢你的解答！
