### ISSUE TITLE
HID 设备初始化失败

### ISSUE THREAD

**Issue by Chinvaejay** [Sucareto/Android_HID_Keyboard#5]
小米12pro 天玑版, 给了root权限, 提示HID 设备初始化失败

**Comment by Sucareto** [comment]
需要先安装[USB Gadget Tool](https://github.com/tejado/android-usb-gadget)，并检查是否支持。
然后在 USB Gadget Tool 内添加 Mouse & Keyboard 功能并成功启用后，再打开本软件。
